name: Wakatime Readme

# on:
#   watch:
#     types: started
#   push:
#     branches: [ master ]
#   schedule:
#     - cron: '* * * * *'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "True"
